### ISSUE TITLE
Controls don't stay connected.

### ISSUE THREAD

**Issue by supersonicth** [Firebottle/BeamChatPlays#10]
I setup an Undertale stream, and left the controls alone. However, after about 2-3 hours, the connection to interactive would be lost. Please fix this so we can run 24/7 streams

**Comment by Firebottle** [comment]
24/7 un-attended streams can be a bad idea with interactive going. All kinds of issues could happen, such as the game closing down, which could result in your channel being suspended for violating the TOS.

With that said, the tool shouldn't disconnect at random. So, I'll be working in a way to automatically connect.

**Comment by Firebottle** [comment]
Ready for next release. Added some basic reconnect on timeout error and reset errors. These are usually caused my internet blips or beam messing with interactive. So, now the app will wait 5 seconds and then try to reconnect.
