### ISSUE TITLE
Button Presses Not Sent

### ISSUE THREAD

**Issue by kylethemurphy** [Firebottle/BeamChatPlays#16]
Hello,

I haven't done extensive testing, but I can successfully connect BCP to Beam and an emulator, but after just a couple keystrokes it seems to lose connection. I went simple and tried Nestopia and Virtua NES so there would be a limited amount of button presses. I followed your YouTube video to see how to do a basic setup and think I have everything set right but I'm not completely sure. 

So, not sure if it's a bug or if it's me.

**Comment by sorryaboutyourcats** [comment]
Hey Kyle - sorry you're having issues; let's see if we can figure this out!

The best way to test the input is from a different computer, tablet or phone. 

Set up BeamChatPlays like you had before, but instead of the emulator, use Notepad - this will rule out compatibility issues. Also be sure to leave it focused.

From another device, hit the buttons (for testing purposes, use wasd keys instead of, say, arrow keys). Do you see the keys being pressed in Notepad?

If not, check the log within BeamChatPlays and see if it states anything.

Let me know your results after testing!

**Comment by Firebottle** [comment]
<3 @sorryaboutyourcats thanks for the help.

**Comment by kylethemurphy** [comment]
Hey @sorryaboutyourcats 

Forgot to mention that my original testing was from my phone.

So, I tested it with notepad. All of the inputs work when pressed but my directional buttons send 2-4 characters at a time. My gamepad buttons send 1-2 key presses at a time.  The log confirmed that it was receiving those multiple presses as well. 

Not sure how that translated to not being responsive through the emulator originally though.

**Comment by slinkonage** [comment]
Okay so I have discovered something. I had the same problem. Again, notepad was working fine, taking in keypresses nicely.

With the emulator I tried (VisualboyAdvance) I noticed a button press would get sent once but then never again. I pressed the 4 buttons for A, B, Select and Start, and the emulator went into a reset loop, suggesting that the button presses were being held down in the emulator, hence why they would only work once. Again, this isn't occurring outside of the emulator.

**Comment by Firebottle** [comment]
Okay yep, this is the same issue that occurs in Farming Sim 15 and GTA V. I'm pretty sure that this is a limitation of Robotjs and the way those games are handling keypresses. 

For now I don't have a fix for it. I tried to find a workaround the first time this was reported but I have a bad feeling robotjs just won't work with certain games.

The workaround is doing something like what probable does with beam keyboardz. Make the app work with many keypress libraries. I can do this as well, but it's going to take quite a bit of time to rewrite things.

**Comment by Firebottle** [comment]
Putting this here for reference. KBM-Robot might be a library we can incorporate to work with games like the ones you guys are using. I'm going to move this into the release cycle to make it so you can choose either library. 

https://github.com/kylepaulsen/kbm-robot

**Comment by sorryaboutyourcats** [comment]
At least from messing with Interactive-Keyboard, I noticed that snes9x & ePSXe work, but Bizhawk did not - even when using kbm-robot. Have you guys tried using other emulators?

**Comment by kylethemurphy** [comment]
I only tried Nestopia and Virtua NES thus far. Hopefully I'll have some time to do testing on other emulators this week.

**Comment by sorryaboutyourcats** [comment]
@kylethemurphy I'll do some testing on the emulators you listed as well to see if I can find a workaround.
To add to my list of working emulators - project64k, snes9x & ePSXe work with robot-js.

Eventually we should create a list of compatible games and applications that work. =D

**Comment by Firebottle** [comment]
Thanks for the help all! If you can find a workaround for robot-js that would be great. I tried for a few hours when I first ran into the issue and came up with nothing.

Next release, if all goes well, I'm going to have an option to toggle between robot-js and kbm-robot which should help with support for some of these.

**Comment by sorryaboutyourcats** [comment]
There were only two ghetto workarounds I found:

**Using GoToMyPC to push the keys remotely**
Basically you use two computers, with the tool running on one and Tachyon running on the other; the key-presses enter one computer and spit out to the other computer.

Using this method I was able to get every game to work, including people playing on my PS4 and considering it was all local, the added lag was not noticeable; this did not work via RDP or TeamViewer though.

**AutoHotKey script to remap the key**
Games were now able to accept input after this - though the one problem is that you cannot hold down keys. Yeah, pretty crappy. This means it'll really only work for turn-based games. It's better to use AutoHotKey for other things like emulating mouse clicks instead.

If I find any other workarounds, I will let you know!

**Comment by sorryaboutyourcats** [comment]
Actually I'm getting the same issue - in DiRT 3, if you press any of the keys, it'll register only one press but no hold; however, **it DOES register the hold using interactive-keyboard.**

Keep in mind that I am using robot-js as the input handler for interactive-keyboard.

**Comment by Firebottle** [comment]
Okay, robot-js and robotjs are two different libraries. I'll take a look at the other library.

**Comment by sorryaboutyourcats** [comment]
@Firebottle Sorry, I just read that you had asked me to test robotjs instead - I will do that later today.

**Comment by sorryaboutyourcats** [comment]
@Firebottle I can't test this efficiently, because even when I change the handler to "fdosofdsaofas" in the game's json file, interactive-keyboard still works.

So regardless of what handler I type in, robot-js, robotjs, kbm-robot or tacosforever, it works the same.

Sorry man - I cannot give you legit info here.

**Comment by Firebottle** [comment]
Ah okay, so he must have gotten rid of the option to change it. I'll check with probable and get his notes on everything when he gets back home. Right now he's at minecon.

The tacosforever keyboard emulator does sound promising though.

**Comment by sorryaboutyourcats** [comment]
With the new version of interactive-keyboard - the handler can now be changed!

However - I tried robot-js, robotjs & kbm-robot and they all appear to work with Snes9X, you can press and hold keys indefinitely. I suppose the problem lies somewhere else then?

If you need me to test anything else, let me know!

**Comment by Firebottle** [comment]
Thanks again! I'll look into it. This one is a little hard to test because it requires an emulator which I can't really get my hands on while I'm at work haha... gives me a lot less time to actually do some testing.

**Comment by twitchplayskh** [comment]
can you not run a  emulator from a usb stick or is it more like if they catch me doing this at work sort of thing

**Comment by Firebottle** [comment]
It's more like "if they catch me at work". FYI though, I did start on the work for this on Saturday. I spent most of the day refactoring the code to make it so I can set up multiple handlers. Basically, I had to rearrange all the code and change how it works. So far it's looking pretty good.

You can see where I'm at so far by taking a look at the project tasklist.
https://github.com/Firebottle/BeamChatPlays/projects/1

**Comment by Firebottle** [comment]
Just released a new version for you guys to try out. I was able to successfully control super mario world on snes9x with both robotjs and the newly added kbm-robot handler.

If the default robotjs doesnt work in your emulator give kbm-robot a try for me. Let me know if there are any issues or if it works for you.

https://github.com/Firebottle/BeamChatPlays/releases/tag/0.6.0-beta

**Comment by Firebottle** [comment]
Alright, it's been about a week and no one has mentioned anything. I'm going to go ahead and close this one. If you run into any issues go ahead and open a new bug.
