### ISSUE TITLE
Invalid key using numpad characters

### ISSUE THREAD

**Issue by sorryaboutyourcats** [Firebottle/BeamChatPlays#19]
'Invalid Key' on buttons using the numpad keys (this was pasted from the JSON in Beam's developer lab.)

![image](https://cloud.githubusercontent.com/assets/13334925/18413239/1800f054-7770-11e6-98b6-a116bcd31841.png)

[overwatch.txt](https://github.com/Firebottle/BeamChatPlays/files/465614/overwatch.txt)

**Comment by Firebottle** [comment]
Thanks! I tried to catch as many of those as possible but I knew there would be more. I'll get this fixed.

**Comment by Firebottle** [comment]
Easy fix. JSON import will support numpad keys in next release.
