### ISSUE TITLE
Application (.exe) Error on Launch

### ISSUE THREAD

**Issue by BringtheGame** [Firebottle/BeamChatPlays#24]
When trying to run the .exe I receive this error window:

![bcp error message](https://cloud.githubusercontent.com/assets/22310355/18655556/e394217a-7eb7-11e6-825a-48de2537f4b4.png)

**Comment by Firebottle** [comment]
Try downloading the "ia32" [version here.](https://github.com/Firebottle/BeamChatPlays/releases/download/0.5.4-beta/BeamChatPlays-win32-ia32.zip) Let me know if that works.

**Comment by BringtheGame** [comment]
That is the version I was using, but I tried deleting and re-downloading.  Unzipped to a different place to see if that would change anything.  Unfortunately, I've got the same result.

**Comment by Firebottle** [comment]
No problem! Let me know if you have any other issues.
