### ISSUE TITLE
Emulator control woes.

### ISSUE THREAD

**Issue by TheClassicalGod** [Firebottle/BeamChatPlays#26]
I'm not sure exactly where the issue may lie on this one, honestly. It might not be anything within your control at all and could be on the Beam end or just the emulators themselves. I set up a control scheme so people could control player 2 for the SNES version of Teenage Mutant Ninja Turles IV: Turtles in Time, which turned out to be awesome and blew my mind. I thank you for helping to make that happen. lol

Where things started getting weird was trying other emulators. I've tried multiple NES emulators and one or two Gameboy emulators. I've created whole new control mappings to be sure and tried different polling methods to see if it would correct the issue. What ends up happening every time is that a button can be pressed once and then it just no longer does anything. Sometimes the button gets stuck and you'll continuously move, but most times you just cant do anything beyond pressing each button once.

I wasn't able to find that anyone else has experienced this issue, so it could entirely be something I am doing wrong. Any input would be appreciated.

**Comment by sorryaboutyourcats** [comment]
[This is currently an issue](https://github.com/Firebottle/BeamChatPlays/issues/16) and might have something to do with the handler used [robot-js VS robotjs].

The only solution for games that require holding is to use [interactive-keyboard](https://github.com/ProbablePrime/interactive-keyboard). If you need assistance setting that up you can check out my guide [here](http://www.sorryaboutyourcats.wtf/blog/beam-interactive-streaming-how-to-set-it-up/).

If you'd rather wait for a solution using BeamChatPlays, please follow [issue 16](https://github.com/Firebottle/BeamChatPlays/issues/16) for updates.

**Comment by TheClassicalGod** [comment]
Wow. That was a quick response. Thank you. I'll give that a try and see how it goes.

**Comment by Firebottle** [comment]
Thanks for the report! Yeah, right now I'm hunting through various control emulators to see if I can find something that works better for most people. Hopefully I'll be able to get around to that soon.

I'm going to go ahead and close this since there is an open issue already.
