### ISSUE TITLE
No confirmation appears, a pop-up doesn't show I'm not logged in, Can't login no matter what.

### ISSUE THREAD

**Issue by ElementTimes682** [Firebottle/BeamChatPlays#27]
I tried 3 different ways to try to get it working.
1.) the usual process of logging in. 
2.) Running it in admin and then tried logging in all available ways.
3.) through discord linked account or twitter linked account.
Number 3 stops working when it pops up and nothing loaded. Waited about 30-60 seconds. Did not work.
EDIT: I CAN"T LOGIN NO MATTER WHAT

**Comment by Firebottle** [comment]
Did you watch the tutorial video? https://www.youtube.com/watch?v=mYx4loPyh5A

Is the problem that you can't log in? Or is the problem that your controls stop working? You've got two different issues and I'm not sure which is the problem.

**Comment by ElementTimes682** [comment]
OAuth? It doesn't pop up a confirmation screen and it says I have to login. But I can't. I can only login with Discord and Twitter. 
![image](https://cloud.githubusercontent.com/assets/5264475/19609426/25406db2-97a5-11e6-8225-a52d6550da16.png)

**Comment by Firebottle** [comment]
So when you log in with any of those does it put your icon onto the login page? Do you have your username and password for beam instead of logging in with one of the other services?

**Comment by ElementTimes682** [comment]
1.) No, Because I can't get past the login screen.
2.) I did, but I signed up with Discord at first. I went to the account and changed the password since I didn't think there was a password.

**Comment by ElementTimes682** [comment]
Apparently the problem is since I signed up with Discord, I had to use the reset password link to do it, Apparently Beam did not detect that there wasn't a password since i signed up with Discord. Issue closed. Don't reply.
