### ISSUE TITLE
OAuth Login

### ISSUE THREAD

**Issue by xKells** [Firebottle/BeamChatPlays#9]
When i click to login it pops up and it hides itself or if i can see it, it does not load. Tried restarting, same. Im on Win 10 running 64.

**Comment by Firebottle** [comment]
Thanks! I've had one other person report this so far as well. Not sure what's causing it but I'll see if I can reproduce.

**Comment by Firebottle** [comment]
Until I can figure out what is causing this issue I'm going to add in the option to use username/password instead of oauth.

**Comment by xKells** [comment]
If it helps I can make a video or try something. I tried this on my work pc and worked great. Thanks for your hard work on this! Looks awesome

**Comment by Firebottle** [comment]
I just updated the app and messed with the way the login works a bit. Can you try out the new version and let me know if it works for you?

**Comment by Firebottle** [comment]
I haven't heard any other reports of this issue since the last update. I'm going to move it out of the release cycle for now unless you're still having the issue.

**Comment by Firebottle** [comment]
Closing, haven't heard of any other reports in the last month.
